#!/bin/bash
# Quick QA Workflow for MA Crossover Baseline EA v1.0
# This script provides a step-by-step checklist for controlled testing

echo "======================================================================"
echo "  MA Crossover Baseline EA v1.0 - QA Workflow Checklist"
echo "======================================================================"
echo ""

# Color codes for readability
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 PHASE 1: PURE MA BASELINE (Deterministic)${NC}"
echo "--------------------------------------------------------------------"
echo "Goal: Establish repeatable performance floor"
echo ""
echo "1. Compilation:"
echo "   □ Open MetaEditor"
echo "   □ Compile TickPhysics_Crypto_SelfHealing_Crossover_EA_v1_0.mq5"
echo "   □ Verify no errors"
echo ""
echo "2. Backtest Setup (Strategy Tester):"
echo "   □ Symbol: ETHUSD (or your preferred crypto pair)"
echo "   □ Timeframe: M5"
echo "   □ Date Range: 3 months (e.g., 2024-10-01 to 2025-01-01)"
echo "   □ Model: Every tick"
echo ""
echo "3. Input Parameters (Phase 1):"
echo "   □ InpUsePhysics = false"
echo "   □ InpUseSelfHealing = false"
echo "   □ InpUseMAEntry = true"
echo "   □ InpUseMAExit = true"
echo "   □ InpMAFast_Entry = 25"
echo "   □ InpMASlow_Entry = 100"
echo "   □ InpMAFast_Exit = 25"
echo "   □ InpMASlow_Exit = 50"
echo "   □ InpEnableSignalLog = true"
echo "   □ InpEnableTradeLog = true"
echo "   □ InpSignalLogFile = \"TP_Crypto_Signals_Baseline.csv\""
echo "   □ InpTradeLogFile = \"TP_Crypto_Trades_Baseline.csv\""
echo ""
echo "4. Run Backtest:"
echo "   □ Start backtest"
echo "   □ Monitor Experts log for MA crossover signals"
echo "   □ Verify trades executed"
echo "   □ Wait for completion"
echo ""
echo "5. Verify CSV Output:"
echo "   □ Navigate to MT5 Files folder:"
echo "     C:\\Users\\<YourName>\\AppData\\Roaming\\MetaQuotes\\Terminal\\<ID>\\MQL5\\Files\\"
echo "   □ Check TP_Crypto_Signals_Baseline.csv exists"
echo "   □ Check TP_Crypto_Trades_Baseline.csv exists"
echo "   □ Open CSVs in Excel/text editor to verify data"
echo ""
echo "6. Python Analysis:"
echo "   □ Copy CSVs to /Users/patjohnston/ai-trading-platform/MQL5/"
echo "   □ Run: python analyze_backtest.py --trades TP_Crypto_Trades_Baseline.csv"
echo "   □ Run: python dashboard.py"
echo "   □ Document baseline metrics (win rate, profit factor, max DD)"
echo ""
echo "7. Repeatability Test:"
echo "   □ Re-run backtest with same settings"
echo "   □ Compare CSVs: should be IDENTICAL"
echo "   □ Confirm deterministic behavior"
echo ""
echo -e "${GREEN}✅ Phase 1 Complete: Baseline Established${NC}"
echo ""
echo ""

echo -e "${BLUE}📋 PHASE 2: MA + PHYSICS ENHANCEMENT (Compare)${NC}"
echo "--------------------------------------------------------------------"
echo "Goal: Measure impact of physics filters"
echo ""
echo "1. Input Parameters (Phase 2):"
echo "   □ InpUsePhysics = true         ← CHANGED"
echo "   □ InpUseSelfHealing = false"
echo "   □ InpUseMAEntry = true"
echo "   □ InpUseMAExit = true"
echo "   □ InpSignalLogFile = \"TP_Crypto_Signals_Physics.csv\"  ← CHANGED"
echo "   □ InpTradeLogFile = \"TP_Crypto_Trades_Physics.csv\"    ← CHANGED"
echo "   □ Keep all other parameters same as Phase 1"
echo ""
echo "2. Indicator Setup (if using):"
echo "   □ Compile TickPhysics_Crypto_Indicator_v2_1.mq5"
echo "   □ Verify InpUseTickPhysicsIndicator = true"
echo "   □ OR set InpUseTickPhysicsIndicator = false to skip indicator"
echo ""
echo "3. Run Backtest:"
echo "   □ Use SAME date range as Phase 1"
echo "   □ Use SAME symbol and timeframe"
echo "   □ Start backtest"
echo "   □ Expect FEWER trades (physics filters reduce signals)"
echo ""
echo "4. Python Analysis & Comparison:"
echo "   □ Run: python analyze_backtest.py --trades TP_Crypto_Trades_Physics.csv"
echo "   □ Compare to Phase 1 metrics:"
echo "     - Win Rate: Should improve"
echo "     - Max Drawdown: Should reduce"
echo "     - Profit Factor: Should improve"
echo "     - Total Trades: Should decrease"
echo "   □ Document improvements (or lack thereof)"
echo ""
echo -e "${GREEN}✅ Phase 2 Complete: Physics Impact Measured${NC}"
echo ""
echo ""

echo -e "${BLUE}📋 PHASE 3: MA + PHYSICS + LEARNING (Advanced)${NC}"
echo "--------------------------------------------------------------------"
echo "Goal: Measure adaptive learning effectiveness"
echo ""
echo "1. Input Parameters (Phase 3):"
echo "   □ InpUsePhysics = true"
echo "   □ InpUseSelfHealing = true      ← CHANGED"
echo "   □ InpEnableLearning = true      ← CHANGED"
echo "   □ InpLearningFile = \"TP_Learning_v22.json\""
echo "   □ InpSignalLogFile = \"TP_Crypto_Signals_Learning.csv\"  ← CHANGED"
echo "   □ InpTradeLogFile = \"TP_Crypto_Trades_Learning.csv\"    ← CHANGED"
echo "   □ Keep all other parameters same as Phase 2"
echo ""
echo "2. Run Backtest:"
echo "   □ Use SAME date range as Phase 1 & 2"
echo "   □ Monitor learning state updates (JSON file)"
echo "   □ Expect NON-DETERMINISTIC behavior (parameters adapt)"
echo ""
echo "3. Python Analysis & Comparison:"
echo "   □ Run: python analyze_backtest.py --trades TP_Crypto_Trades_Learning.csv"
echo "   □ Compare to Phase 1 & 2:"
echo "     - Does learning improve win rate?"
echo "     - Does it adapt to regime changes?"
echo "     - Is it robust or overfitted?"
echo "   □ Document learning effectiveness"
echo ""
echo -e "${GREEN}✅ Phase 3 Complete: Learning Impact Measured${NC}"
echo ""
echo ""

echo -e "${YELLOW}📊 FINAL COMPARISON MATRIX${NC}"
echo "--------------------------------------------------------------------"
echo "Metric                | Baseline | Physics | Learning"
echo "----------------------|----------|---------|----------"
echo "Win Rate (%)          |   ___    |   ___   |   ___"
echo "Profit Factor         |   ___    |   ___   |   ___"
echo "Max Drawdown (%)      |   ___    |   ___   |   ___"
echo "Total Trades          |   ___    |   ___   |   ___"
echo "Avg Trade Duration    |   ___    |   ___   |   ___"
echo "Repeatability         | ✅ 100%  | ✅ 100% | ❌ N/A"
echo ""
echo "Recommendation:"
echo "□ Use Baseline if: You want predictable, simple strategy"
echo "□ Use Physics if: You want better quality, fewer false signals"
echo "□ Use Learning if: You want adaptive optimization (advanced)"
echo ""
echo ""

echo -e "${BLUE}🛠️ TROUBLESHOOTING${NC}"
echo "--------------------------------------------------------------------"
echo "Issue: CSV logs not created"
echo "  → Check InpEnableSignalLog = true and InpEnableTradeLog = true"
echo "  → Verify file paths in inputs"
echo "  → Check MT5 Files folder permissions"
echo ""
echo "Issue: No trades generated"
echo "  → Verify MA crossover occurs in data (check chart manually)"
echo "  → Lower physics filter thresholds (if enabled)"
echo "  → Check Experts log for errors"
echo ""
echo "Issue: Indicator not found"
echo "  → Compile TickPhysics_Crypto_Indicator_v2_1.mq5"
echo "  → OR set InpUseTickPhysicsIndicator = false"
echo ""
echo "Issue: Python scripts fail"
echo "  → Check CSV file paths"
echo "  → Install dependencies: pip install pandas matplotlib numpy"
echo "  → Verify CSV headers match expected format"
echo ""
echo ""

echo -e "${GREEN}======================================================================"
echo "  QA Workflow Ready - Start with Phase 1!"
echo "======================================================================${NC}"
echo ""
echo "For detailed documentation, see:"
echo "  - MA_CROSSOVER_BASELINE_v1_0_SUMMARY.md"
echo "  - QA_GUIDE.md"
echo "  - BUGFIX_SUMMARY_v2_*.md"
echo ""
